"""add brand_id to hero_maps and persona_id to hero_map_entries

Revision ID: 0806b52fcef6
Revises: b8cac2d3245e
Create Date: 2026-03-22 06:47:24.139501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0806b52fcef6'
down_revision: Union[str, Sequence[str], None] = 'b8cac2d3245e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daypart_schedules', sa.Column('object_type', sa.String(), nullable=True))
    op.add_column('hero_map_entries', sa.Column('persona_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_hero_map_entries_persona_id'), 'hero_map_entries', ['persona_id'], unique=False)
    op.create_foreign_key(None, 'hero_map_entries', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.add_column('hero_maps', sa.Column('brand_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_hero_maps_brand_id'), 'hero_maps', ['brand_id'], unique=False)
    op.create_foreign_key(None, 'hero_maps', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero_maps', type_='foreignkey')
    op.drop_index(op.f('ix_hero_maps_brand_id'), table_name='hero_maps')
    op.drop_column('hero_maps', 'brand_id')
    op.drop_constraint(None, 'hero_map_entries', type_='foreignkey')
    op.drop_index(op.f('ix_hero_map_entries_persona_id'), table_name='hero_map_entries')
    op.drop_column('hero_map_entries', 'persona_id')
    op.drop_column('daypart_schedules', 'object_type')
    # ### end Alembic commands ###
