"""add unique constraints on persona fb_page_id and domain_id

Revision ID: 128b580edf6f
Revises: 2ee78d2baaa4
Create Date: 2026-03-06 16:03:12.641922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128b580edf6f'
down_revision: Union[str, Sequence[str], None] = '2ee78d2baaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_domain_id'), table_name='personas')
    op.create_index(op.f('ix_personas_domain_id'), 'personas', ['domain_id'], unique=True)
    op.create_unique_constraint(None, 'personas', ['fb_page_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personas', type_='unique')
    op.drop_index(op.f('ix_personas_domain_id'), table_name='personas')
    op.create_index(op.f('ix_personas_domain_id'), 'personas', ['domain_id'], unique=False)
    # ### end Alembic commands ###
