"""add ta_integration_code to cloaker_campaigns

Revision ID: 287ff4a627df
Revises: 889fab196acf
Create Date: 2026-03-10 20:29:15.339693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287ff4a627df'
down_revision: Union[str, Sequence[str], None] = '889fab196acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloaker_campaigns', sa.Column('ta_integration_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloaker_campaigns', 'ta_integration_code')
    # ### end Alembic commands ###
