"""add unique constraint on domain ad_account_id

Revision ID: 2ee78d2baaa4
Revises: db32f79f6e33
Create Date: 2026-03-06 16:00:52.879178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee78d2baaa4'
down_revision: Union[str, Sequence[str], None] = 'db32f79f6e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'domains', ['ad_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domains', type_='unique')
    # ### end Alembic commands ###
