"""add delivery_method to cloaker_campaigns

Revision ID: 3d9fc3ac9e05
Revises: 287ff4a627df
Create Date: 2026-03-11 19:18:24.041710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9fc3ac9e05'
down_revision: Union[str, Sequence[str], None] = '287ff4a627df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
