"""add_daily_stats_table

Revision ID: 4a86b89df967
Revises: b658005a91be
Create Date: 2026-03-30 17:16:20.243563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a86b89df967'
down_revision: Union[str, Sequence[str], None] = 'b658005a91be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_sync_daily_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('ad_account_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('adset_id', sa.String(), nullable=True),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('impressions', sa.String(), nullable=True),
    sa.Column('clicks', sa.String(), nullable=True),
    sa.Column('spend', sa.String(), nullable=True),
    sa.Column('ctr', sa.String(), nullable=True),
    sa.Column('cpc', sa.String(), nullable=True),
    sa.Column('cpm', sa.String(), nullable=True),
    sa.Column('reach', sa.String(), nullable=True),
    sa.Column('results', sa.Integer(), nullable=True),
    sa.Column('purchase_revenue', sa.Float(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('action_values', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'object_id', 'object_type', 'ad_account_id', name='uq_daily_stats')
    )
    op.create_index(op.f('ix_fb_sync_daily_stats_ad_account_id'), 'fb_sync_daily_stats', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_fb_sync_daily_stats_campaign_id'), 'fb_sync_daily_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_fb_sync_daily_stats_date'), 'fb_sync_daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_fb_sync_daily_stats_object_id'), 'fb_sync_daily_stats', ['object_id'], unique=False)
    op.create_index(op.f('ix_facebook_ads_fb_ad_id'), 'facebook_ads', ['fb_ad_id'], unique=False)
    op.create_index(op.f('ix_facebook_adsets_fb_adset_id'), 'facebook_adsets', ['fb_adset_id'], unique=False)
    op.create_index(op.f('ix_facebook_campaigns_fb_campaign_id'), 'facebook_campaigns', ['fb_campaign_id'], unique=False)
    op.create_index(op.f('ix_generated_ads_ad_bundle_id'), 'generated_ads', ['ad_bundle_id'], unique=False)
    op.create_index(op.f('ix_personas_is_active'), 'personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_personas_offer'), 'personas', ['offer'], unique=False)
    op.create_index(op.f('ix_scheduled_budget_changes_status'), 'scheduled_budget_changes', ['status'], unique=False)
    op.create_index(op.f('ix_swipe_files_collection'), 'swipe_files', ['collection'], unique=False)
    op.create_index(op.f('ix_swipe_files_niche'), 'swipe_files', ['niche'], unique=False)
    op.create_index(op.f('ix_swipe_files_platform'), 'swipe_files', ['platform'], unique=False)
    op.create_index(op.f('ix_swipe_files_source_url'), 'swipe_files', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_files_source_url'), table_name='swipe_files')
    op.drop_index(op.f('ix_swipe_files_platform'), table_name='swipe_files')
    op.drop_index(op.f('ix_swipe_files_niche'), table_name='swipe_files')
    op.drop_index(op.f('ix_swipe_files_collection'), table_name='swipe_files')
    op.drop_index(op.f('ix_scheduled_budget_changes_status'), table_name='scheduled_budget_changes')
    op.drop_index(op.f('ix_personas_offer'), table_name='personas')
    op.drop_index(op.f('ix_personas_is_active'), table_name='personas')
    op.drop_index(op.f('ix_generated_ads_ad_bundle_id'), table_name='generated_ads')
    op.drop_index(op.f('ix_facebook_campaigns_fb_campaign_id'), table_name='facebook_campaigns')
    op.drop_index(op.f('ix_facebook_adsets_fb_adset_id'), table_name='facebook_adsets')
    op.drop_index(op.f('ix_facebook_ads_fb_ad_id'), table_name='facebook_ads')
    op.drop_index(op.f('ix_fb_sync_daily_stats_object_id'), table_name='fb_sync_daily_stats')
    op.drop_index(op.f('ix_fb_sync_daily_stats_date'), table_name='fb_sync_daily_stats')
    op.drop_index(op.f('ix_fb_sync_daily_stats_campaign_id'), table_name='fb_sync_daily_stats')
    op.drop_index(op.f('ix_fb_sync_daily_stats_ad_account_id'), table_name='fb_sync_daily_stats')
    op.drop_table('fb_sync_daily_stats')
    # ### end Alembic commands ###
