"""add_cloaker_campaigns_table

Revision ID: 4d0d898c566e
Revises: 128b580edf6f
Create Date: 2026-03-06 17:02:26.874664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0d898c566e'
down_revision: Union[str, Sequence[str], None] = '128b580edf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloaker_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('ta_campaign_number', sa.Integer(), nullable=True),
    sa.Column('ta_campaign_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('safe_page_url', sa.String(), nullable=True),
    sa.Column('money_page_url', sa.String(), nullable=True),
    sa.Column('safe_page_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('worker_deployed', sa.Boolean(), nullable=True),
    sa.Column('worker_route', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloaker_campaigns')
    # ### end Alembic commands ###
