"""add_headline_presets_table

Revision ID: 4de4d0d19771
Revises: ca36387688ad
Create Date: 2026-03-28 22:54:53.473127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de4d0d19771'
down_revision: Union[str, Sequence[str], None] = 'ca36387688ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headline_presets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('offer', sa.String(), nullable=False),
    sa.Column('headlines', sa.JSON(), nullable=False),
    sa.Column('primary_texts', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headline_presets_offer'), 'headline_presets', ['offer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headline_presets_offer'), table_name='headline_presets')
    op.drop_table('headline_presets')
    # ### end Alembic commands ###
