"""add_deadbolt_to_cloaker_campaigns

Revision ID: 879df6c6af8a
Revises: a746219a213f
Create Date: 2026-03-10 14:57:42.639172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879df6c6af8a'
down_revision: Union[str, Sequence[str], None] = 'a746219a213f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloaker_campaigns', sa.Column('deadbolt', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloaker_campaigns', 'deadbolt')
    # ### end Alembic commands ###
