"""add ad_account_id persona_id fb_page_id to cloaker_campaigns

Revision ID: 889fab196acf
Revises: b4c5d6e7f8a9
Create Date: 2026-03-10 17:59:55.409435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889fab196acf'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloaker_campaigns', sa.Column('ad_account_id', sa.String(), nullable=True))
    op.add_column('cloaker_campaigns', sa.Column('persona_id', sa.String(), nullable=True))
    op.add_column('cloaker_campaigns', sa.Column('fb_page_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cloaker_campaigns', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cloaker_campaigns', type_='foreignkey')
    op.drop_column('cloaker_campaigns', 'fb_page_id')
    op.drop_column('cloaker_campaigns', 'persona_id')
    op.drop_column('cloaker_campaigns', 'ad_account_id')
    # ### end Alembic commands ###
