"""add_ta_rules_json_to_cloaker_campaigns

Revision ID: 936b45763d4f
Revises: 879df6c6af8a
Create Date: 2026-03-10 15:29:31.861471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936b45763d4f'
down_revision: Union[str, Sequence[str], None] = '879df6c6af8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloaker_campaigns', sa.Column('ta_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloaker_campaigns', 'ta_rules')
    # ### end Alembic commands ###
