"""add safe_page_id to cloaker_campaigns

Revision ID: a746219a213f
Revises: 4d0d898c566e
Create Date: 2026-03-10 14:11:44.230437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a746219a213f'
down_revision: Union[str, Sequence[str], None] = '4d0d898c566e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloaker_campaigns', sa.Column('safe_page_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cloaker_campaigns', 'safe_pages', ['safe_page_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cloaker_campaigns', type_='foreignkey')
    op.drop_column('cloaker_campaigns', 'safe_page_id')
    # ### end Alembic commands ###
