"""add_today_stats_to_sync_tables

Revision ID: a97697680af6
Revises: 0806b52fcef6
Create Date: 2026-03-28 21:25:27.521206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97697680af6'
down_revision: Union[str, Sequence[str], None] = '0806b52fcef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cloaker_campaigns_domain_id'), 'cloaker_campaigns', ['domain_id'], unique=False)
    op.create_index(op.f('ix_cloaker_campaigns_persona_id'), 'cloaker_campaigns', ['persona_id'], unique=False)
    op.create_index(op.f('ix_cloaker_campaigns_safe_page_id'), 'cloaker_campaigns', ['safe_page_id'], unique=False)
    op.create_index(op.f('ix_domain_dns_records_domain_id'), 'domain_dns_records', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domains_brand_id'), 'domains', ['brand_id'], unique=False)
    op.create_index(op.f('ix_domains_hosting_account_id'), 'domains', ['hosting_account_id'], unique=False)
    op.add_column('fb_sync_ads', sa.Column('today_date', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_spend', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_impressions', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_clicks', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_ctr', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_cpc', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_cpm', sa.String(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_results', sa.Integer(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_purchase_revenue', sa.Float(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_actions', sa.JSON(), nullable=True))
    op.add_column('fb_sync_ads', sa.Column('today_action_values', sa.JSON(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_date', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_spend', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_impressions', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_clicks', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_ctr', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_cpc', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_cpm', sa.String(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_results', sa.Integer(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_purchase_revenue', sa.Float(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_actions', sa.JSON(), nullable=True))
    op.add_column('fb_sync_adsets', sa.Column('today_action_values', sa.JSON(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_date', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_spend', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_impressions', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_clicks', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_ctr', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_cpc', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_cpm', sa.String(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_results', sa.Integer(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_purchase_revenue', sa.Float(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_actions', sa.JSON(), nullable=True))
    op.add_column('fb_sync_campaigns', sa.Column('today_action_values', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_tracked_pages_brand_id'), 'tracked_pages', ['brand_id'], unique=False)
    op.create_index(op.f('ix_tracked_pages_connection_id'), 'tracked_pages', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tracked_pages_domain_id'), 'tracked_pages', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_pages_domain_id'), table_name='tracked_pages')
    op.drop_index(op.f('ix_tracked_pages_connection_id'), table_name='tracked_pages')
    op.drop_index(op.f('ix_tracked_pages_brand_id'), table_name='tracked_pages')
    op.drop_column('fb_sync_campaigns', 'today_action_values')
    op.drop_column('fb_sync_campaigns', 'today_actions')
    op.drop_column('fb_sync_campaigns', 'today_purchase_revenue')
    op.drop_column('fb_sync_campaigns', 'today_results')
    op.drop_column('fb_sync_campaigns', 'today_cpm')
    op.drop_column('fb_sync_campaigns', 'today_cpc')
    op.drop_column('fb_sync_campaigns', 'today_ctr')
    op.drop_column('fb_sync_campaigns', 'today_clicks')
    op.drop_column('fb_sync_campaigns', 'today_impressions')
    op.drop_column('fb_sync_campaigns', 'today_spend')
    op.drop_column('fb_sync_campaigns', 'today_date')
    op.drop_column('fb_sync_adsets', 'today_action_values')
    op.drop_column('fb_sync_adsets', 'today_actions')
    op.drop_column('fb_sync_adsets', 'today_purchase_revenue')
    op.drop_column('fb_sync_adsets', 'today_results')
    op.drop_column('fb_sync_adsets', 'today_cpm')
    op.drop_column('fb_sync_adsets', 'today_cpc')
    op.drop_column('fb_sync_adsets', 'today_ctr')
    op.drop_column('fb_sync_adsets', 'today_clicks')
    op.drop_column('fb_sync_adsets', 'today_impressions')
    op.drop_column('fb_sync_adsets', 'today_spend')
    op.drop_column('fb_sync_adsets', 'today_date')
    op.drop_column('fb_sync_ads', 'today_action_values')
    op.drop_column('fb_sync_ads', 'today_actions')
    op.drop_column('fb_sync_ads', 'today_purchase_revenue')
    op.drop_column('fb_sync_ads', 'today_results')
    op.drop_column('fb_sync_ads', 'today_cpm')
    op.drop_column('fb_sync_ads', 'today_cpc')
    op.drop_column('fb_sync_ads', 'today_ctr')
    op.drop_column('fb_sync_ads', 'today_clicks')
    op.drop_column('fb_sync_ads', 'today_impressions')
    op.drop_column('fb_sync_ads', 'today_spend')
    op.drop_column('fb_sync_ads', 'today_date')
    op.drop_index(op.f('ix_domains_hosting_account_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_brand_id'), table_name='domains')
    op.drop_index(op.f('ix_domain_dns_records_domain_id'), table_name='domain_dns_records')
    op.drop_index(op.f('ix_cloaker_campaigns_safe_page_id'), table_name='cloaker_campaigns')
    op.drop_index(op.f('ix_cloaker_campaigns_persona_id'), table_name='cloaker_campaigns')
    op.drop_index(op.f('ix_cloaker_campaigns_domain_id'), table_name='cloaker_campaigns')
    # ### end Alembic commands ###
