"""add_cached_pixels_table

Revision ID: b658005a91be
Revises: 4de4d0d19771
Create Date: 2026-03-28 23:19:24.058142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b658005a91be'
down_revision: Union[str, Sequence[str], None] = '4de4d0d19771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_pixels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fb_pixel_id', sa.String(), nullable=False),
    sa.Column('ad_account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fb_pixel_id', 'ad_account_id', name='uq_cached_pixel')
    )
    op.create_index(op.f('ix_cached_pixels_ad_account_id'), 'cached_pixels', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_cached_pixels_fb_pixel_id'), 'cached_pixels', ['fb_pixel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cached_pixels_fb_pixel_id'), table_name='cached_pixels')
    op.drop_index(op.f('ix_cached_pixels_ad_account_id'), table_name='cached_pixels')
    op.drop_table('cached_pixels')
    # ### end Alembic commands ###
