"""add hero_maps and hero_map_entries tables

Revision ID: b8cac2d3245e
Revises: 3d9fc3ac9e05
Create Date: 2026-03-22 05:29:43.665631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cac2d3245e'
down_revision: Union[str, Sequence[str], None] = '3d9fc3ac9e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_maps', sa.Column('base_image_url', sa.String(), nullable=True))
    op.add_column('hero_maps', sa.Column('layout', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero_maps', 'layout')
    op.drop_column('hero_maps', 'base_image_url')
    # ### end Alembic commands ###
