"""add_winner_fields_to_personas

Revision ID: ca36387688ad
Revises: a97697680af6
Create Date: 2026-03-28 22:13:16.805435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca36387688ad'
down_revision: Union[str, Sequence[str], None] = 'a97697680af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('is_winner', sa.Boolean(), nullable=True))
    op.add_column('personas', sa.Column('winner_notes', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('winner_proven_offers', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('winner_promoted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'winner_promoted_at')
    op.drop_column('personas', 'winner_proven_offers')
    op.drop_column('personas', 'winner_notes')
    op.drop_column('personas', 'is_winner')
    # ### end Alembic commands ###
