"""add persona new fields and persona_images table

Revision ID: db32f79f6e33
Revises: b7c8d9e0f1a2
Create Date: 2026-03-06 14:40:21.833474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db32f79f6e33'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_images_persona_id'), 'persona_images', ['persona_id'], unique=False)
    op.drop_table('cp_ad_creatives')
    op.drop_table('clickflare_config')
    op.drop_index(op.f('ix_command_center_data_user_id'), table_name='command_center_data')
    op.drop_table('command_center_data')
    op.drop_table('persona_affiliate_urls')
    op.drop_table('cp_overlap_logs')
    op.drop_table('cp_advertorials')
    op.drop_table('cp_accounts')
    op.drop_table('clickflare_mappings')
    op.create_foreign_key(None, 'persona_rotation_log', 'persona_posts', ['target_post_id'], ['id'], ondelete='SET NULL')
    op.add_column('personas', sa.Column('subject_gender', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('subject_age', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('posting_about', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('before_weight', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('after_weight', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('total_lost', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('timeline_months', sa.Integer(), nullable=True))
    op.add_column('personas', sa.Column('start_month', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('body_type_before', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('body_type_after', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('hair', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('ethnicity', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('distinguishing_features', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('shame_moment', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('authority_figure', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('domain_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_personas_domain_id'), 'personas', ['domain_id'], unique=False)
    op.drop_constraint(op.f('personas_brand_id_fkey'), 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'personas', 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.create_foreign_key(op.f('personas_brand_id_fkey'), 'personas', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personas_domain_id'), table_name='personas')
    op.drop_column('personas', 'domain_id')
    op.drop_column('personas', 'authority_figure')
    op.drop_column('personas', 'shame_moment')
    op.drop_column('personas', 'distinguishing_features')
    op.drop_column('personas', 'ethnicity')
    op.drop_column('personas', 'hair')
    op.drop_column('personas', 'body_type_after')
    op.drop_column('personas', 'body_type_before')
    op.drop_column('personas', 'start_month')
    op.drop_column('personas', 'timeline_months')
    op.drop_column('personas', 'total_lost')
    op.drop_column('personas', 'after_weight')
    op.drop_column('personas', 'before_weight')
    op.drop_column('personas', 'posting_about')
    op.drop_column('personas', 'subject_age')
    op.drop_column('personas', 'subject_gender')
    op.drop_constraint(None, 'persona_rotation_log', type_='foreignkey')
    op.create_table('clickflare_mappings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('facebook_ad_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tracking_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cf_offer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cf_campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['facebook_ad_id'], ['facebook_ads.id'], name=op.f('clickflare_mappings_facebook_ad_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clickflare_mappings_pkey'))
    )
    op.create_table('cp_accounts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vertical_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vertical_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offer_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('persona_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_occupation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_location_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_location_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_backstory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persona_pain_point', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persona_discovery_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('persona_emotional_hook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_scheme', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('font_pair', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('brand_voice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('design_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('brand_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overlap_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overlap_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cp_accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cp_accounts_pkey'))
    )
    op.create_table('cp_advertorials',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('legal_pages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cp_accounts.id'], name=op.f('cp_advertorials_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cp_advertorials_pkey'))
    )
    op.create_table('cp_overlap_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_a_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_b_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('overlap_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overlap_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_a_id'], ['cp_accounts.id'], name=op.f('cp_overlap_logs_account_a_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['account_b_id'], ['cp_accounts.id'], name=op.f('cp_overlap_logs_account_b_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cp_overlap_logs_pkey'))
    )
    op.create_table('persona_affiliate_urls',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('offer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('persona_affiliate_urls_pkey'))
    )
    op.create_table('command_center_data',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('xp_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('achievements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('command_center_data_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('command_center_data_pkey'))
    )
    op.create_index(op.f('ix_command_center_data_user_id'), 'command_center_data', ['user_id'], unique=True)
    op.create_table('clickflare_config',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tracking_domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('facebook_traffic_source_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('facebook_pixel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clickflare_config_pkey'))
    )
    op.create_table('cp_ad_creatives',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('headline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_text_overlay', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cp_accounts.id'], name=op.f('cp_ad_creatives_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cp_ad_creatives_pkey'))
    )
    op.drop_index(op.f('ix_persona_images_persona_id'), table_name='persona_images')
    op.drop_table('persona_images')
    # ### end Alembic commands ###
